# Generated by Django 5.1.15 on 2026-04-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='Hargrove Realty Group', help_text="Sender name shown in the recipient's inbox.", max_length=100)),
                ('from_email', models.EmailField(help_text='The email address emails are sent from (e.g. info@hargrovrealtygroup.com).', max_length=254)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', help_text='SMTP server hostname. Gmail: smtp.gmail.com', max_length=200)),
                ('smtp_port', models.PositiveIntegerField(default=587, help_text='SMTP port. Use 587 for TLS (recommended) or 465 for SSL.')),
                ('use_tls', models.BooleanField(default=True, help_text='Enable TLS encryption (recommended for port 587).')),
                ('use_ssl', models.BooleanField(default=False, help_text='Enable SSL encryption (use for port 465). Do not enable both TLS and SSL.')),
                ('email_host_user', models.EmailField(help_text='The Gmail (or other provider) account used to authenticate with the SMTP server.', max_length=254)),
                ('email_host_password', models.CharField(help_text='Gmail App Password — 16-character password generated at myaccount.google.com/apppasswords. Do NOT use your regular Gmail password.', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Only the active configuration is used. Disable to pause all outgoing email.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configuration',
            },
        ),
    ]
