# Generated by Django 4.2.30 on 2026-05-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='display_name',
            field=models.CharField(default='Hasker & Co. Realty Group', help_text="Sender name shown in the recipient's inbox.", max_length=100),
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='from_email',
            field=models.EmailField(help_text='The email address emails are sent from (e.g. info@haskerrealtygroup.com).', max_length=254),
        ),
    ]
