# Generated by Django 5.1.15 on 2026-04-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='stripe_invoice_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_receipt_url',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stripe_payment_intent_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHECK', 'Check')], max_length=20),
        ),
    ]
