# Generated by Django 4.2.30 on 2026-05-18 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0008_remove_lead_email_marketing_opted_out_and_more'),
        ('transactions', '0004_paymentmethodconfig_bank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed breakdown of the charges.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, help_text='e.g. "Monthly Rent - August 2026"', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Directly assign an invoice to a user profile.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_image',
            field=models.CharField(blank=True, help_text='Cloudinary URL of the receipt/screenshot', max_length=500),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(blank=True, help_text='User-provided Ref ID, CashTag, or PayPal email', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='rental_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.rentalapplication'),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='transactions.transaction'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHECK', 'Check'), ('PAYPAL', 'PayPal'), ('VENMO', 'Venmo'), ('CASHAPP', 'CashApp'), ('CHIME', 'Chime')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_VERIFICATION', 'Pending Verification'), ('SUCCESSFUL', 'Successful'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.transaction'),
        ),
        migrations.AlterField(
            model_name='paymentmethodconfig',
            name='display_name',
            field=models.CharField(help_text='e.g. "Venmo", "Cash App"', max_length=50),
        ),
    ]
