# Generated by Django 4.2.30 on 2026-05-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_invoice_description_invoice_title_invoice_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='allocated_items',
            field=models.JSONField(blank=True, default=list, help_text='Line item descriptions covered by this payment, e.g. ["Security Deposit", "Pet Fee"]'),
        ),
    ]
