# Generated by Django 5.1.15 on 2026-04-21 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_condition_cross_street_tour_360_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['latitude'], name='properties__latitud_689e5b_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['longitude'], name='properties__longitu_90ba49_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties__price_32e7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_published'], name='properties__is_publ_b4a635_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['bedrooms'], name='properties__bedroom_6cd35c_idx'),
        ),
    ]
