# Generated by Django 6.0 on 2026-04-13 23:16

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contract'), ('RECEIPT', 'Receipt'), ('AGREEMENT', 'Agreement'), ('ID_DOCUMENT', 'ID Document'), ('PROOF_OF_FUNDS', 'Proof of Funds'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.client')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Document',
                'verbose_name_plural': 'Client Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
