# Generated by Django 6.0 on 2026-04-14 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cell_phone', models.CharField(max_length=20)),
                ('home_phone', models.CharField(blank=True, max_length=20)),
                ('has_kids', models.BooleanField(default=False)),
                ('number_of_kids', models.PositiveIntegerField(default=0)),
                ('present_address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('move_in_date', models.DateField()),
                ('intended_stay_duration', models.CharField(help_text='e.g. "12 months"', max_length=100)),
                ('months_rent_upfront', models.PositiveIntegerField(default=1)),
                ('has_pets', models.BooleanField(default=False)),
                ('pet_description', models.CharField(blank=True, max_length=300)),
                ('smokes', models.BooleanField(default=False)),
                ('drinks', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NEW', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('certification_text', models.CharField(blank=True, help_text='Auto-populated: applicant certifies information is true.', max_length=500)),
                ('application_pdf', models.CharField(blank=True, help_text='Cloudinary URL of the generated application PDF.', max_length=500)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_applications', to='crm.lead')),
                ('rental_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_applications', to='properties.property')),
            ],
            options={
                'verbose_name': 'Rental Application',
                'verbose_name_plural': 'Rental Applications',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status'], name='crm_rentala_status_248b50_idx'), models.Index(fields=['email'], name='crm_rentala_email_f98237_idx'), models.Index(fields=['rental_property', 'status'], name='crm_rentala_rental__159f70_idx')],
            },
        ),
    ]
