# Generated by Django 4.2.30 on 2026-05-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_email_marketing_opted_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='email_marketing_opted_out',
        ),
        migrations.AlterField(
            model_name='lead',
            name='detected_city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
