# Generated by Django 4.2.30 on 2026-05-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_rentalapplication_expanded'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalapplication',
            name='ssn_encrypted',
            field=models.TextField(blank=True, default='', help_text='Full SSN encrypted at rest (Fernet/AES). Never edit directly. Superadmin-only via admin panel.'),
        ),
    ]
