# Generated by Django 4.2.30 on 2026-05-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_add_ssn_encrypted_to_rental_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='has_pets',
            field=models.BooleanField(blank=True, help_text='Whether the prospect has pets — affects property eligibility', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='move_in_timeline',
            field=models.CharField(blank=True, choices=[('ASAP', 'As Soon As Possible'), ('1_3_MONTHS', '1–3 Months'), ('3_6_MONTHS', '3–6 Months'), ('6_PLUS', '6+ Months'), ('JUST_BROWSING', 'Just Browsing')], help_text='How soon the prospect wants to move — key urgency signal', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='occupants_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Total number of people who will live in the property', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_contact',
            field=models.CharField(blank=True, choices=[('PHONE', 'Phone Call'), ('TEXT', 'Text / SMS'), ('EMAIL', 'Email')], help_text='How the prospect prefers to be reached', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='referral_source',
            field=models.CharField(blank=True, help_text='How the prospect heard about us (self-reported)', max_length=150),
        ),
    ]
