# Generated by Django 4.2.30 on 2026-05-22 00:00

import apps.crm.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_add_lead_enrichment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('code', models.CharField(default=apps.crm.models._generate_referral_code, help_text='Unique code shared in referral links (?ref=CODE)', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='Referral code used when this lead was captured (links to a Referrer)', max_length=20),
        ),
        migrations.CreateModel(
            name='ReferralPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONVERTED', 'Tenant Converted'), ('PAID', 'Commission Paid'), ('VOID', 'Void')], default='PENDING', max_length=20)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, help_text='Actual rent amount — set when tenant pays first month', max_digits=10, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.4, help_text='Fraction of monthly rent paid per month (default 40%)', max_digits=4)),
                ('commission_months', models.PositiveSmallIntegerField(default=2, help_text='Number of months the commission applies to (default 2)')),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated: monthly_rent × commission_months × commission_rate', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_payout', to='crm.lead')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='crm.referrer')),
                ('rental_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_payout', to='crm.rentalapplication')),
            ],
            options={
                'verbose_name': 'Referral Payout',
                'verbose_name_plural': 'Referral Payouts',
                'ordering': ['-created_at'],
            },
        ),
    ]
